site_name: Flort by Watkins Labs
site_description: Professional file concatenation and project overview tool for AI workflows and enterprise development
site_author: Chris Watkins - Watkins Labs
site_url: https://watkinslabs.github.io/flort/

# Repository
repo_name: watkinslabs/flort
repo_url: https://github.com/watkinslabs/flort
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Chris Watkins - Watkins Labs. All rights reserved.

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
    
  logo: assets/flort-logo.png
  favicon: assets/flort-logo.png
  
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  # Git plugins disabled until repository has commit history
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: timeago
  # - git-committers:
  #     repository: watkinslabs/flort
  #     branch: main
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters: ["!^_"]
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

# Customization
extra:
  homepage: https://watkinslabs.github.io/flort/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/watkinslabs/flort
      name: View source on GitHub
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/flort/
      name: Download from PyPI
    - icon: fontawesome/solid/paper-plane
      link: mailto:chris@watkinslabs.com
      name: Contact Chris Watkins
    - icon: fontawesome/solid/building
      link: https://watkinslabs.com
      name: Watkins Labs
  
  version:
    provider: mike
    default: stable
  
  generator: false
  
extra_css:
  - stylesheets/custom.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: watkinslabs
      repo: flort
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
  - User Guide:
    - Command Line: usage.md
    - Interactive UI: ui-guide.md
    - File Filtering: filtering.md
    - Output Formats: output-formats.md
  - Examples:
    - Use Cases & Examples: examples.md
  - API Reference:
    - Overview: api/overview.md
    - Core API: api/core.md
    - File Operations: api/files.md
    - Utilities: api/utils.md
  - Development:
    - Contributing: contributing.md
    - Changelog: changelog.md
  - Support:
    - Troubleshooting: troubleshooting.md

# Watch additional files in dev mode
watch:
  - flort/
  - README.md
  - CHANGELOG.md
  - LICENSE