name: ✨ Feature Request
description: Suggest an idea or enhancement for Flort
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide detailed information to help us understand your request.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please verify these before submitting
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: This feature doesn't exist in the current version
          required: true
        - label: I have considered if this could be solved with existing features
          required: false

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New command-line option
        - Interactive UI enhancement
        - New output format
        - Performance improvement
        - API enhancement
        - Documentation improvement
        - Integration with other tools
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe what you're trying to accomplish.
      placeholder: "I'm always frustrated when... / I need to be able to... / It would be helpful if..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What other approaches have you thought about?
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        Example 1: When working with large codebases...
        Example 2: For LLM context preparation...
        Example 3: In CI/CD pipelines...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: Proposed CLI/API Design
      description: If applicable, show how the feature would work
      placeholder: |
        # Command line usage:
        flort . --new-option value
        
        # API usage:
        from flort import new_function
        result = new_function(params)
      render: bash
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my use case
        - Critical - Cannot use Flort without this
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low - Small change or addition
        - Medium - Moderate development effort
        - High - Significant development effort
        - Unknown - Not sure
    validations:
      required: false

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to help implement this feature?
      options:
        - label: I would be willing to submit a pull request
        - label: I can help with testing
        - label: I can help with documentation
        - label: I can provide feedback during development

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, mockups, or examples
      placeholder: Links to similar features in other tools, mockups, detailed workflows, etc.
    validations:
      required: false